[package]
name = "dx_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.6.0", features = [] }
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
table_derive = { path = "./reslt_derive" }
tokio = { version = "1.44.2", features = ["full"] }
