[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = [] }
ui = { workspace = true }
web-sys = "0.3.77"
wasm-bindgen = "0.2"

[features]
default = ["web"]
web = ["dioxus/web"]

